name: Build and Push YOLO GPU Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: rebaracr.azurecr.io
        username: rebaracr
        password: SxKmm5YVO+PIYiQWbmee8dMAn6gq/Ex5OfF7I0tVCz+ACRDv1B1W  # 🔥 temporary only!

    - name: Build and push container
      run: |
        docker build -t rebaracr.azurecr.io/yolo-gpu-infer:latest .
        docker push rebaracr.azurecr.io/yolo-gpu-infer:latest
